apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: chill-crate
stringData:
  KC_BOOTSTRAP_ADMIN_USERNAME: ""
  KC_BOOTSTRAP_ADMIN_PASSWORD: ""
  KC_DB: ""
  KC_DB_URL: ""
  KC_DB_USERNAME: ""
  KC_DB_PASSWORD: ""
