apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: chill-crate-api-updater
  namespace: argocd
spec:
  writeBackConfig:
    method: "argocd"
  applicationRefs:
    - namePattern: chill-crate-api
      images:
        - alias: api
          imageName: ghcr.io/mic615/chill-crate-api:latest
          commonUpdateSettings:
            updateStrategy: digest
          manifestTargets:
            helm:
              name: "image.repository"
              tag: "image.tag"
